#Eight Project --> 
#spring:
# security:
#  user:
#   name: sumit
#   password: 12345
   
server:
 port: 8090

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/springsecurity
  username: root
  password: admin
 jpa:
  properties: 
   hibernates: 
    dialect : org.hibernate.dialect.MySQL8Dialect
  generate-ddl: true
  show-sql: true
  hibernate: 
   ddl-auto: update
   
logging:
 level:
  org:
   springframework:
    security:
     web:
      FilterChainProxy : DEBUG